[workspace]
members = [
  "crates/ego-core",
  "crates/ego-p2p",
  "crates/ego-consensus",
  "crates/ego-rollup",
  "crates/ego-ffi",
  "crates/ego-vm",
  "crates/ego-evm",
  "bins/ego-node",
  "crates/urego-compiler",
  "bins/urego",
  "crates/ego-zk",
  "bins/ego-cli",
  "bins/ego-relay",
  "crates/ego-typed-signing",
]

exclude = [
  "services/indexer",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Ego-Blockchain Team"]

[workspace.dependencies]
anyhow = "1"
thiserror = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tokio = { version = "1.47.1", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
bytes = "1.10.1"
yamux = "0.13.4"
libp2p = { version = "0.54", features = ["tokio", "yamux", "noise", "dns", "quic", "gossipsub", "kad", "macros"] }
blake2 = "0.10"

[profile.dev.package.pqcrypto-dilithium]
opt-level = 3

[profile.dev.package.pqcrypto-kyber]
opt-level = 3

[profile.dev.package.pqcrypto-sphincsplus]
opt-level = 3

[profile.dev.package.pqcrypto-internals]
opt-level = 3
