name = "ego/p2p-cardano"
version = "0.0.0"
compiler = "v1.1.24"
plutus = "v3"
license = "Apache-2.0"
description = "Ego P2P market escrow validator"

[repository]
user = "ego"
project = "p2p-cardano"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v4.0.0"
source = "github"

[config]
