//! In-circuit Poseidon, replicating `light-poseidon`'s circom construction.
//!
//! # Why this exists
//!
//! The shielded pool hashes commitments and nullifiers natively with
//! `light-poseidon`'s `new_circom` construction (Tornado Cash's Poseidon over
//! BN254). A withdrawal proof has to recompute those hashes *inside* the
//! circuit, and the in-circuit result must equal the native one bit for bit or
//! a perfectly valid note fails to verify with no clue why.
//!
//! No library provides that gadget. `light-poseidon` is native-only, and
//! `ark-crypto-primitives`' Poseidon gadget uses a different sponge
//! construction, so identical constants still produce a different output.
//!
//! So this replicates `light-poseidon`'s construction exactly, read from its
//! source rather than inferred: state seeded with the domain tag, then the
//! inputs; half the full rounds, all the partial rounds, the other half of the
//! full rounds; round constants indexed `ark[round * width + i]`; the S-box on
//! every element in a full round and on `state[0]` alone in a partial one; the
//! MDS matrix as `new[i] = Σ_j state[j] * mds[i][j]`; and `state[0]` as the
//! output.
//!
//! # How it is verified
//!
//! `light-poseidon` is the reference. The tests below hash random inputs both
//! natively and in-circuit and require equality, which is precisely what a
//! published reference vector would give and can be generated without limit.
//! The oracle itself is first checked against the test vector its own
//! documentation publishes, so the comparison is not circular.
//!
//! The constants come from the same table `light-poseidon` uses, generated by
//! the Poseidon authors' own `generate_parameters_grain.sage`, so no round
//! constant or MDS entry is transcribed by hand here.
//!
//! # What this does not establish
//!
//! Agreement with the native hash shows the gadget *computes* Poseidon
//! correctly. It says nothing about whether a circuit built on it is *sound*,
//! meaning that no witness outside the intended set satisfies the constraints.
//! That is the property a shielded pool actually depends on, it is not
//! something tests can establish, and it is why the pool stays disabled until
//! the finished circuit has been reviewed by somebody who does this for a
//! living.

use ark_bn254::Fr;
use ark_ff::Zero;
use ark_r1cs_std::fields::fp::FpVar;
use ark_r1cs_std::prelude::*;
use ark_relations::r1cs::SynthesisError;
use light_poseidon::parameters::bn254_x5::get_poseidon_parameters;

/// Domain tags for the shielded pool. These must equal the constants in
/// `ego-desktop/src-tauri/src/shielded.rs`; a mismatch means the circuit proves
/// a hash the pool never computed.
pub const SHIELDED_COMMITMENT_DOMAIN: u64 = 1;
pub const SHIELDED_NULLIFIER_DOMAIN: u64 = 2;

/// The Poseidon parameters for a given input count, in the layout the gadget
/// consumes. Read from `light-poseidon`'s table, never constructed here.
pub struct PoseidonGadgetParams {
    ark: Vec<Fr>,
    mds: Vec<Vec<Fr>>,
    full_rounds: usize,
    partial_rounds: usize,
    width: usize,
}

impl PoseidonGadgetParams {
    /// Parameters for hashing `nr_inputs` field elements, matching
    /// `Poseidon::<Fr>::new_circom(nr_inputs)` / `with_domain_tag_circom`.
    pub fn circom(nr_inputs: usize) -> Result<Self, String> {
        let width = nr_inputs + 1;
        let p = get_poseidon_parameters::<Fr>(width as u8).map_err(|e| e.to_string())?;
        // The S-box below is hard-coded as x^5 because this is the bn254_x5
        // table. Refuse anything else rather than silently computing a
        // different function.
        if p.alpha != 5 {
            return Err(format!("expected alpha = 5 for bn254_x5, got {}", p.alpha));
        }
        if p.width != width {
            return Err(format!("parameter width {} does not match requested {}", p.width, width));
        }
        Ok(Self {
            ark: p.ark,
            mds: p.mds,
            full_rounds: p.full_rounds,
            partial_rounds: p.partial_rounds,
            width: p.width,
        })
    }

    pub fn width(&self) -> usize {
        self.width
    }
}

/// x^5, the bn254_x5 S-box. Three multiplication constraints when `x` is a
/// variable; folds to a constant, costing nothing, when `x` is one.
fn sbox(x: &FpVar<Fr>) -> FpVar<Fr> {
    let x2 = x * x;
    let x4 = &x2 * &x2;
    &x4 * x
}

/// Hash `inputs` under `domain_tag`, in-circuit, exactly as
/// `light_poseidon::Poseidon::with_domain_tag_circom(inputs.len(), domain_tag).hash(inputs)`
/// does natively.
pub fn poseidon_hash_gadget(
    params: &PoseidonGadgetParams,
    domain_tag: Fr,
    inputs: &[FpVar<Fr>],
) -> Result<FpVar<Fr>, SynthesisError> {
    if inputs.len() + 1 != params.width {
        // A programming error, not a runtime condition: the params were built
        // for a different input count.
        return Err(SynthesisError::Unsatisfiable);
    }
    let width = params.width;

    let mut state: Vec<FpVar<Fr>> = Vec::with_capacity(width);
    state.push(FpVar::Constant(domain_tag));
    state.extend_from_slice(inputs);

    let all_rounds = params.full_rounds + params.partial_rounds;
    let half = params.full_rounds / 2;

    let add_round_constants = |state: &mut Vec<FpVar<Fr>>, round: usize| {
        for (i, s) in state.iter_mut().enumerate() {
            *s = &*s + params.ark[round * width + i];
        }
    };

    let mix = |state: &mut Vec<FpVar<Fr>>| {
        let mut next = Vec::with_capacity(width);
        for row in params.mds.iter().take(width) {
            let mut acc = FpVar::Constant(Fr::zero());
            for (j, s) in state.iter().enumerate() {
                acc = &acc + &(s * row[j]);
            }
            next.push(acc);
        }
        *state = next;
    };

    for round in 0..half {
        add_round_constants(&mut state, round);
        for s in state.iter_mut() {
            *s = sbox(s);
        }
        mix(&mut state);
    }

    for round in half..half + params.partial_rounds {
        add_round_constants(&mut state, round);
        state[0] = sbox(&state[0]);
        mix(&mut state);
    }

    for round in half + params.partial_rounds..all_rounds {
        add_round_constants(&mut state, round);
        for s in state.iter_mut() {
            *s = sbox(s);
        }
        mix(&mut state);
    }

    Ok(state[0].clone())
}

/// In-circuit `Note::commitment()`: `Poseidon(COMMITMENT_DOMAIN, value, secret, rho)`.
pub fn commitment_gadget(
    value: &FpVar<Fr>,
    secret: &FpVar<Fr>,
    rho: &FpVar<Fr>,
) -> Result<FpVar<Fr>, SynthesisError> {
    let params = PoseidonGadgetParams::circom(3).map_err(|_| SynthesisError::Unsatisfiable)?;
    poseidon_hash_gadget(
        &params,
        Fr::from(SHIELDED_COMMITMENT_DOMAIN),
        &[value.clone(), secret.clone(), rho.clone()],
    )
}

/// In-circuit `Note::nullifier()`: `Poseidon(NULLIFIER_DOMAIN, secret, rho)`.
pub fn nullifier_gadget(secret: &FpVar<Fr>, rho: &FpVar<Fr>) -> Result<FpVar<Fr>, SynthesisError> {
    let params = PoseidonGadgetParams::circom(2).map_err(|_| SynthesisError::Unsatisfiable)?;
    poseidon_hash_gadget(
        &params,
        Fr::from(SHIELDED_NULLIFIER_DOMAIN),
        &[secret.clone(), rho.clone()],
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use ark_relations::r1cs::{ConstraintSystem, ConstraintSystemRef};
    use ark_std::{test_rng, UniformRand};
    use light_poseidon::{Poseidon, PoseidonBytesHasher, PoseidonHasher};

    /// The native reference.
    fn native(domain: Fr, inputs: &[Fr]) -> Fr {
        let mut p = Poseidon::<Fr>::with_domain_tag_circom(inputs.len(), domain).unwrap();
        p.hash(inputs).unwrap()
    }

    /// The gadget, on freshly allocated witnesses. Returns the computed value,
    /// whether the constraint system is satisfied, and how many constraints
    /// it took.
    fn in_circuit(domain: Fr, inputs: &[Fr]) -> (Fr, bool, usize, ConstraintSystemRef<Fr>) {
        let cs = ConstraintSystem::<Fr>::new_ref();
        let params = PoseidonGadgetParams::circom(inputs.len()).unwrap();
        let vars: Vec<FpVar<Fr>> = inputs
            .iter()
            .map(|x| FpVar::new_witness(cs.clone(), || Ok(*x)).unwrap())
            .collect();
        let out = poseidon_hash_gadget(&params, domain, &vars).unwrap();
        let value = out.value().unwrap();
        let ok = cs.is_satisfied().unwrap();
        let n = cs.num_constraints();
        (value, ok, n, cs)
    }

    /// Before trusting light-poseidon as the oracle, check it reproduces the
    /// test vector published in its own documentation. Otherwise the equality
    /// tests below would only prove that two things agree, not that either is
    /// right.
    #[test]
    fn the_oracle_reproduces_its_own_documented_vector() {
        let mut p = Poseidon::<Fr>::new_circom(2).unwrap();
        let h = p.hash_bytes_be(&[&[1u8; 32], &[2u8; 32]]).unwrap();
        let documented: [u8; 32] = [
            13, 84, 225, 147, 143, 138, 140, 28, 125, 235, 94, 3, 85, 242, 99, 25, 32, 123, 132,
            254, 156, 162, 206, 27, 38, 231, 53, 200, 41, 130, 25, 144,
        ];
        assert_eq!(h, documented, "light-poseidon disagrees with its own published vector");
    }

    #[test]
    fn gadget_equals_native_for_two_inputs() {
        let mut rng = test_rng();
        for _ in 0..32 {
            let inputs = [Fr::rand(&mut rng), Fr::rand(&mut rng)];
            let domain = Fr::from(SHIELDED_NULLIFIER_DOMAIN);
            let (got, ok, _, _) = in_circuit(domain, &inputs);
            assert!(ok, "constraint system must be satisfied by an honest witness");
            assert_eq!(got, native(domain, &inputs), "in-circuit hash differs from native");
        }
    }

    /// The commitment shape: three inputs, so width 4 and a different row of
    /// the parameter table. If the flat `ark` indexing were wrong it would show
    /// here even if it happened to work for width 3.
    #[test]
    fn gadget_equals_native_for_three_inputs() {
        let mut rng = test_rng();
        for _ in 0..32 {
            let inputs = [Fr::rand(&mut rng), Fr::rand(&mut rng), Fr::rand(&mut rng)];
            let domain = Fr::from(SHIELDED_COMMITMENT_DOMAIN);
            let (got, ok, _, _) = in_circuit(domain, &inputs);
            assert!(ok);
            assert_eq!(got, native(domain, &inputs));
        }
    }

    /// The domain tag is what stops a commitment being reinterpreted as a
    /// nullifier. It must change the output, and it must do so identically in
    /// both implementations.
    #[test]
    fn the_domain_tag_separates_and_matches_native() {
        let mut rng = test_rng();
        let inputs = [Fr::rand(&mut rng), Fr::rand(&mut rng)];
        let d1 = Fr::from(SHIELDED_COMMITMENT_DOMAIN);
        let d2 = Fr::from(SHIELDED_NULLIFIER_DOMAIN);
        let (g1, _, _, _) = in_circuit(d1, &inputs);
        let (g2, _, _, _) = in_circuit(d2, &inputs);
        assert_ne!(g1, g2, "different domains must give different hashes");
        assert_eq!(g1, native(d1, &inputs));
        assert_eq!(g2, native(d2, &inputs));
    }

    /// Zero inputs are a classic edge case for hash gadgets: an implementation
    /// that accidentally short-circuits on zero would agree with native on
    /// random inputs and diverge here.
    #[test]
    fn gadget_equals_native_on_all_zero_inputs() {
        let inputs = [Fr::zero(), Fr::zero()];
        let domain = Fr::from(SHIELDED_NULLIFIER_DOMAIN);
        let (got, ok, _, _) = in_circuit(domain, &inputs);
        assert!(ok);
        assert_eq!(got, native(domain, &inputs));
    }

    /// The whole reason for Poseidon: a few hundred constraints per hash rather
    /// than tens of thousands. Pinned exactly so an accidental extra
    /// multiplication cannot creep in unnoticed.
    ///
    /// Every S-box is three multiplications. The domain tag is a constant, so
    /// in the very first full round `state[0]`'s S-box folds at compile time
    /// and costs nothing; every other S-box acts on a variable.
    #[test]
    fn constraint_count_is_exactly_what_the_construction_implies() {
        let mut rng = test_rng();
        for nr_inputs in [2usize, 3] {
            let inputs: Vec<Fr> = (0..nr_inputs).map(|_| Fr::rand(&mut rng)).collect();
            let params = PoseidonGadgetParams::circom(nr_inputs).unwrap();
            let (_, ok, n, _) = in_circuit(Fr::from(1u64), &inputs);
            assert!(ok);
            let width = params.width;
            let sboxes = params.full_rounds * width + params.partial_rounds;
            let expected = sboxes * 3 - 3;
            assert_eq!(
                n, expected,
                "width {width}: got {n} constraints, construction implies {expected}"
            );
        }
    }

    /// A wrong-sized input must be refused rather than indexing off the end of
    /// the constant table and computing garbage.
    #[test]
    fn a_mismatched_input_count_is_refused() {
        let cs = ConstraintSystem::<Fr>::new_ref();
        let params = PoseidonGadgetParams::circom(2).unwrap();
        let one = FpVar::new_witness(cs.clone(), || Ok(Fr::from(7u64))).unwrap();
        assert!(poseidon_hash_gadget(&params, Fr::from(1u64), &[one]).is_err());
    }

    /// The two pool-specific wrappers must agree with native for the exact
    /// domain and arity `shielded.rs` uses.
    #[test]
    fn commitment_and_nullifier_gadgets_match_native() {
        let mut rng = test_rng();
        let cs = ConstraintSystem::<Fr>::new_ref();
        let (v, s, r) = (Fr::from(1_000u64), Fr::rand(&mut rng), Fr::rand(&mut rng));
        let vv = FpVar::new_witness(cs.clone(), || Ok(v)).unwrap();
        let sv = FpVar::new_witness(cs.clone(), || Ok(s)).unwrap();
        let rv = FpVar::new_witness(cs.clone(), || Ok(r)).unwrap();

        let c = commitment_gadget(&vv, &sv, &rv).unwrap().value().unwrap();
        let n = nullifier_gadget(&sv, &rv).unwrap().value().unwrap();
        assert!(cs.is_satisfied().unwrap());

        assert_eq!(c, native(Fr::from(SHIELDED_COMMITMENT_DOMAIN), &[v, s, r]));
        assert_eq!(n, native(Fr::from(SHIELDED_NULLIFIER_DOMAIN), &[s, r]));
        assert_ne!(c, n);
    }
}
